name: Publish to npm

on:
  # 1) Trigger this workflow when creating a new GitHub release
  release:
    types: [published]
  # or 2) Alternatively, you could trigger on tag push:
  # push:
  #   tags:
  #     - "v*.*.*"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js 16 (or another version)
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Publish to npm
        run: yarn publish --non-interactive --new-version ${{ steps.get_version.outputs.VERSION }} 
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # If you want to automatically bump the version based on the release tag,
      # you can parse the release tag or rely on a separate step. For instance:
      - name: Get version from tag
        id: get_version
        run: |
          # E.g. if your release tag is "v1.0.3", parse out "1.0.3"
          VERSION="${GITHUB_REF#refs/tags/v}"
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
